[package]
name = "via_protocol_keychron"
description = "VIA protocol extension for Keychron keyboards"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.13.0"
hidapi = "2.6.6"
palette = { version = "0.7.6", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive", "rc"], optional = true }
tracing = "0.1.44"
via-protocol = "0.1.0"

[dev-dependencies]
ctor = "1.0.8"
serial_test = "3.5.0"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[features]
serde = ["dep:serde", "bitflags/serde"]
